// Old Testament
const GENESIS = 'ot/gen',
EXODUS = 'ot/ex',
LEVITICUS = 'ot/lev',
NUMBERS = 'ot/num',
DEUTERONOMY = 'ot/deut',
JOSHUA = 'ot/josh',
JUDGES = 'ot/judg',
RUTH = 'ot/ruth',
FIRST_SAMUEL = 'ot/1-sam',
SECOND_SAMUEL = 'ot/2-sam',
FIRST_KINGS = 'ot/1-kgs',
SECOND_KINGS = 'ot/2-kgs',
FIRST_CHRONICLES = 'ot/1-chr',
SECOND_CHRONICLES = 'ot/2-chr',
EZRA = 'ot/ezra',
NEHEMIAH = 'ot/neh',
ESTHER = 'ot/esth',
JOB = 'ot/job',
PSALMS = 'ot/ps',
PROVERBS = 'ot/prov',
ECCLESIASTES = 'ot/eccl',
ISAIAH = 'ot/isa',
JEREMIAH = 'ot/jer',
LAMENTATIONS = 'ot/lam',
EZEKIEL = 'ot/ezek',
DANIEL = 'ot/dan',
HOSEA = 'ot/hosea',
JOEL = 'ot/joel',
AMOS = 'ot/amos',
OBADIAH = 'ot/obad',
JONAH = 'ot/jonah',
MICAH = 'ot/micah',
NAHUM = 'ot/nahum',
HABAKKUK = 'ot/hab',
ZEPHANIAH = 'ot/zeph',
HAGGAI = 'ot/hag',
ZECHARIAH = 'ot/zech',
MALACHI = 'ot/mal'

const ot = {
  'gen': GENESIS,
  'genesis': GENESIS,
  'ex': EXODUS,
  'exodus': EXODUS,
  'lev': LEVITICUS,
  'leviticus': LEVITICUS,
  'num': NUMBERS,
  'numbers': NUMBERS,
  'deut': DEUTERONOMY,
  'deuteronomy': DEUTERONOMY,
  'josh': JOSHUA,
  'joshua': JOSHUA,
  'judg': JUDGES,
  'judges': JUDGES,
  'ruth': RUTH,
  '1 sam': FIRST_SAMUEL,
  '1 samuel': FIRST_SAMUEL,
  '2 sam': SECOND_SAMUEL,
  '2 samuel': SECOND_SAMUEL,
  '1 kgs': FIRST_KINGS,
  '1 kings': FIRST_KINGS,
  '2 kgs': SECOND_KINGS,
  '2 kings': SECOND_KINGS,
  '1 chr': FIRST_CHRONICLES,
  '1 chronicles': FIRST_CHRONICLES,
  '2 chr': SECOND_CHRONICLES,
  '2 chronicles': SECOND_CHRONICLES,
  'ezra': EZRA,
  'neh': NEHEMIAH,
  'nehemiah': NEHEMIAH,
  'esth': ESTHER,
  'esther': ESTHER,
  'job': JOB,
  'ps': PSALMS,
  'psalms': PSALMS,
  'prov': PROVERBS,
  'proverbs': PROVERBS,
  'eccl': ECCLESIASTES,
  'ecclesiastes': ECCLESIASTES,
  'isa': ISAIAH,
  'isaiah': ISAIAH,
  'jer': JEREMIAH,
  'jeremiah': JEREMIAH,
  'lam': LAMENTATIONS,
  'lamentations': LAMENTATIONS,
  'ezek': EZEKIEL,
  'ezekiel': EZEKIEL,
  'dan': DANIEL,
  'daniel': DANIEL,
  'hosea': HOSEA,
  'joel': JOEL,
  'amos': AMOS,
  'obad': OBADIAH,
  'obadiah': OBADIAH,
  'jonah': JONAH,
  'micah': MICAH,
  'nahum': NAHUM,
  'hab': HABAKKUK,
  'habakkuk': HABAKKUK,
  'zeph': ZEPHANIAH,
  'zephaniah': ZEPHANIAH,
  'hag': HAGGAI,
  'haggai': HAGGAI,
  'zech': ZECHARIAH,
  'zechariah': ZECHARIAH,
  'mal': MALACHI,
  'malachi': MALACHI
}

// new testament
const MATTHEW = 'nt/matt',
MARK = 'nt/mark',
LUKE = 'nt/luke',
JOHN = 'nt/john',
ACTS = 'nt/acts',
ROMANS = 'nt/rom',
FIRST_CORINTHIANS = 'nt/1-cor',
SECOND_CORINTHIANS = 'nt/2-cor',
GALATIANS = 'nt/gal',
EPHESIANS = 'nt/eph',
PHILIPPIANS = 'nt/philip',
COLOSSIANS = 'nt/col',
FIRST_THESSALONIANS = 'nt/1-thes',
SECOND_THESSALONIANS = 'nt/2-thes',
FIRST_TIMOTHY = 'nt/1-tim',
SECOND_TIMOTHY = 'nt/2-tim',
TITUS = 'nt/titus',
PHILEMON = 'nt/philem',
HEBREWS = 'nt/heb',
JAMES = 'nt/james',
FIRST_PETER = 'nt/1-pet',
SECOND_PETER = 'nt/2-pet',
FIRST_JOHN = 'nt/1-jn',
SECOND_JOHN = 'nt/2-jn',
THIRD_JOHN = 'nt/3-jn',
JUDE = 'nt/jude',
REVELATION = 'nt/rev'

const nt = {
  'matt': MATTHEW,
  'matthew': MATTHEW,
  'matthow': MATTHEW,
  'mark': MARK,
  'luke': LUKE,
  'john': JOHN,
  'acts': ACTS,
  'rom': ROMANS,
  'romans': ROMANS,
  '1 cor': FIRST_CORINTHIANS,
  '1 corinthians': FIRST_CORINTHIANS,
  '2 cor': SECOND_CORINTHIANS,
  '2 corinthians': SECOND_CORINTHIANS,
  'gal': GALATIANS,
  'galatians': GALATIANS,
  'eph': EPHESIANS,
  'ephesians': EPHESIANS,
  'philip': PHILIPPIANS,
  'col': COLOSSIANS,
  'colossians': COLOSSIANS,
  '1 thes': FIRST_THESSALONIANS,
  '1 thessalonians': FIRST_THESSALONIANS,
  '2 thes': SECOND_THESSALONIANS,
  '2 thessalonians': SECOND_THESSALONIANS,
  '1 tim': FIRST_TIMOTHY,
  '1 timothy': FIRST_TIMOTHY,
  '2 tim': SECOND_TIMOTHY,
  '2 timothy': SECOND_TIMOTHY,
  'titus': TITUS,
  'philem': PHILEMON,
  'philemon': PHILEMON,
  'heb': HEBREWS,
  'hebrews': HEBREWS,
  'james': JAMES,
  '1 pet': FIRST_PETER,
  '1 peter': FIRST_PETER,
  '2 pet': SECOND_PETER,
  '2 peter': SECOND_PETER,
  '1 jn': FIRST_JOHN,
  '1 john': FIRST_JOHN,
  '2 jn': SECOND_JOHN,
  '2 john': SECOND_JOHN,
  '3 jn': THIRD_JOHN,
  '3 john': THIRD_JOHN,
  'jude': JUDE,
  'rev': REVELATION,
  'revelation': REVELATION,
}

// Book of Mormon
const FIRST_NEPHI = 'bofm/1-ne',
SECOND_NEPHI = 'bofm/2-ne',
JACOB = 'bofm/jacob',
ENOS = 'bofm/enos',
JAROM = 'bofm/jarom',
OMNI = 'bofm/omni',
WORDS_OF_MORMON = 'bofm/of m',
MOSIAH = 'bofm/mosiah',
ALMA = 'bofm/alma',
HELAMAN = 'bofm/hel',
THIRD_NEPHI = 'bofm/3-ne',
FOURTH_NEPHI = 'bofm/4-ne',
MORMON = 'bofm/morm',
ETHER = 'bofm/ether',
MORONI = 'bofm/moro'

const bofm = {
  '1 ne': FIRST_NEPHI,
  '1 nephi': FIRST_NEPHI,
  '2 ne': SECOND_NEPHI,
  '2 nephi': SECOND_NEPHI,
  'jacob': JACOB,
  'enos': ENOS,
  'jarom': JAROM,
  'omni': OMNI,
  'of m': WORDS_OF_MORMON,
  'of mormon': WORDS_OF_MORMON,
  'mosiah': MOSIAH,
  'alma': ALMA,
  'aima': ALMA, // typo
  'hel': HELAMAN,
  'helaman': HELAMAN,
  '3 ne': THIRD_NEPHI,
  '3 nephi': THIRD_NEPHI,
  '4 ne': FOURTH_NEPHI,
  '4 nephi': FOURTH_NEPHI,
  'morm': MORMON,
  'mormon': MORMON,
  'ether': ETHER,
  'moro': MORONI,
  'moroni': MORONI
}

// Doctrine and Covenants
const DOCTRINE_AND_COVENANTS = 'dc-testament/dc',
  OFFICIAL_DECLARATION = 'dc-testament/od'

const dc = {
  'd&c': DOCTRINE_AND_COVENANTS,
  'd&amp;c': DOCTRINE_AND_COVENANTS,
  'dec': DOCTRINE_AND_COVENANTS, // typo
  'dac': DOCTRINE_AND_COVENANTS, // typo
  'd8c': DOCTRINE_AND_COVENANTS, // typo
  '08c': DOCTRINE_AND_COVENANTS, // typo
  'dbc': DOCTRINE_AND_COVENANTS, // typo
  'od': OFFICIAL_DECLARATION
}

// Pearl of Great Price
const MOSES = 'pgp/moses',
  ABRAHAM = 'pgp/abr',
  JOSEPH_SMITH_MATTHEW = 'pgp/js—m',
  JOSEPH_SMITH_HISTORY = 'pgp/js—h',
  ARTICLES_OF_FAITH = 'pgp/a-of-f'

const pgp = {
  'moses': MOSES,
  'm0ses': MOSES, // typo
  'abr': ABRAHAM,
  'js—m': JOSEPH_SMITH_MATTHEW,
  'jst m': JOSEPH_SMITH_MATTHEW,
  'js—h': JOSEPH_SMITH_HISTORY,
  'jsh': JOSEPH_SMITH_HISTORY,
  'j5h': JOSEPH_SMITH_HISTORY, // typo
  'a of f': ARTICLES_OF_FAITH
}

// Other
const JOSEPH_SMITH_TRANSLATION = 'scriptures/jst',
      TOPICAL_GUIDE = 'scriptures/tg',
      BIBLE_DICTIONARY = 'scriptures/bd',
      INDEX_TO_THE_TRIPLE_COMBINATION = 'scriptures/it',
      GUIDE_TO_THE_SCRIPTURES = 'scriptures/gs',
      HISTORY_OF_THE_CHURCH = 'scriptures/hc'

const other = {
  'jst': JOSEPH_SMITH_TRANSLATION, // TODO
  'tg': TOPICAL_GUIDE,
  'bd': BIBLE_DICTIONARY,
  'it': INDEX_TO_THE_TRIPLE_COMBINATION,
  'gs': GUIDE_TO_THE_SCRIPTURES,
  'hc': HISTORY_OF_THE_CHURCH,
}

export default {
  ...ot,
  ...nt,
  ...bofm,
  ...dc,
  ...pgp,
  ...other
}
